# Generated by Django 3.2.5 on 2021-12-17 00:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 12, 17, 1, 15, 24, 811282))),
                ('loan_amount', models.IntegerField()),
            ],
        ),
    ]
