# Generated by Django 3.2.5 on 2021-12-17 01:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_alter_record_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 17, 2, 17, 11, 110244)),
        ),
    ]
