# Generated by Django 3.2.5 on 2021-12-18 14:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_alter_record_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 18, 15, 55, 32, 644602)),
        ),
        migrations.AlterField(
            model_name='record',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.history'),
        ),
    ]
