# Generated by Django 3.2.5 on 2021-12-18 15:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0006_alter_record_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='calc.record'),
        ),
        migrations.AlterField(
            model_name='record',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 18, 16, 6, 22, 643671)),
        ),
        migrations.AlterField(
            model_name='record',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
