# Generated by Django 3.2.5 on 2021-12-18 15:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0007_auto_20211218_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.record'),
        ),
        migrations.AlterField(
            model_name='record',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 18, 16, 43, 0, 775827)),
        ),
    ]
