# Generated by Django 3.2.5 on 2021-12-27 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0011_auto_20211218_1706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='paid_amount',
            new_name='percentage',
        ),
        migrations.AlterField(
            model_name='record',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 27, 15, 45, 38, 322853)),
        ),
    ]
